### ISSUE TITLE
Help understanding some concepts

### ISSUE THREAD

**Issue by TuanaCelik** [masci/banks#25]
Hey @masci - I'm trying to understand some concepts here. I'm a bit confused about which features are pure prompt/chat message creation, vs which ones are eventually doing a call to an LLM under the hood. Can you help me out here and maybe show me where in the codebase I can start looking?
- chat: this only creates Chat Messages, yes? No actual call to an LLM
- Completion: I'm confused with this one.
- generate: there is an eventual call to an LLM
And am I correct in saying that so far the LLMs that is supported is OpenAI models and LiteLLM? 

Finally, with the tool calling within the prompt, does it result in only a prompt with the result of the tool call embedded?

**Comment by masci** [comment]
> 
>     * chat: this only creates Chat Messages, yes? No actual call to an LLM
>
Correct, you get a list of objects that can be used in LLM calls
 
>     * Completion: I'm confused with this one.
> 
This makes an actual LLM call while rendering the prompt. The final, "rendered" text (or chat message) form of the prompt will contain text that comes from an LLM.

>     * generate: there is an eventual call to an LLM
Correct, but this was deprecated in favor of `completion` so you should use that one.

>       And am I correct in saying that so far the LLMs that is supported is OpenAI models and LiteLLM?
> 
Banks supports LiteLLM only, but this means supporting [all these providers](https://docs.litellm.ai/docs/providers)!

> 
> Finally, with the tool calling within the prompt, does it result in only a prompt with the result of the tool call embedded?

The tool call will generate some text and this text can be used inside the prompt while rendering. It's the same concept of the `completion` tag.
